### ISSUE TITLE
The typical usage doesn't work on my machine

### ISSUE THREAD

**Issue by jasonqiu98** [nurturenature/jepsen-docker-workaround#8]
My system: Linux Mint 21

I just followed the typical usage listed in the docs of your project. I ran `lein run serve` and then opened a new terminal to run `lein run test --workload pn-counter`, but then some error happened.

Here is the log (the setup of the Jepsen test is omitted):

```
INFO [2022-09-21 22:29:35,084] jepsen node n2 - jepsen.os.debian n2 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n5 - jepsen.os.debian n5 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n3 - jepsen.os.debian n3 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n4 - jepsen.os.debian n4 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n1 - jepsen.os.debian n1 setting up debian
INFO [2022-09-21 22:29:35,929] jepsen test runner - jepsen.db Tearing down DB
INFO [2022-09-21 22:29:36,029] jepsen test runner - jepsen.db Setting up DB
INFO [2022-09-21 22:29:39,706] jepsen node n4 - jepsen.control.util Starting antidote
INFO [2022-09-21 22:29:39,721] jepsen test runner - jepsen.core Snarfing log files
INFO [2022-09-21 22:29:39,773] jepsen node n4 - jepsen.core downloading /root/antidote/antidote.daemon.log to antidote.daemon.log
WARN [2022-09-21 22:29:39,991] jepsen test runner - jepsen.core Test crashed!
clojure.lang.ExceptionInfo: Command exited with non-zero status 2 on node n4:
sudo -k -S -u root bash -c "cd /; NODE_NAME=antidote@n4. COOKIE=antidote start-stop-daemon --start --background --no-close --make-pidfile --exec bin/antidote  --pidfile /root/antidote/antidote.daemon.pid --chdir /root/antidote --startas bin/antidote -- foreground -kernel logger_level debug -antidote sync_log false >> /root/antidote/antidote.daemon.log 2>&1"

STDIN:
null

STDOUT:


STDERR:

        at slingshot.support$stack_trace.invoke(support.clj:201)
        at jepsen.control.core$throw_on_nonzero_exit.invokeStatic(core.clj:160)
        at jepsen.control.core$throw_on_nonzero_exit.invoke(core.clj:155)
        at jepsen.control$exec_STAR_.invokeStatic(control.clj:145)
        at jepsen.control$exec_STAR_.doInvoke(control.clj:142)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at jepsen.control$exec.invokeStatic(control.clj:161)
        at jepsen.control$exec.doInvoke(control.clj:155)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at jepsen.control.util$start_daemon_BANG_.invokeStatic(util.clj:364)
        at jepsen.control.util$start_daemon_BANG_.doInvoke(util.clj:311)
        at clojure.lang.RestFn.invoke(RestFn.java:722)
        at fuzz_dist.db$db$reify__2703$fn__2707.invoke(db.clj:104)
        at fuzz_dist.db$db$reify__2703.start_BANG_(db.clj:103)
        at fuzz_dist.db$db$reify__2703.setup_BANG_(db.clj:43)
        at jepsen.db$fn__6953$G__6947__6957.invoke(db.clj:12)
        at jepsen.db$fn__6953$G__6946__6962.invoke(db.clj:12)
        at clojure.core$partial$fn__5908.invoke(core.clj:2642)
        at jepsen.control$on_nodes$fn__6824.invoke(control.clj:314)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at dom_top.core$real_pmap_helper$build_thread__406$fn__407.invoke(core.clj:152)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [2022-09-21 22:29:39,992] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
clojure.lang.ExceptionInfo: Command exited with non-zero status 2 on node n4:
sudo -k -S -u root bash -c "cd /; NODE_NAME=antidote@n4. COOKIE=antidote start-stop-daemon --start --background --no-close --make-pidfile --exec bin/antidote  --pidfile /root/antidote/antidote.daemon.pid --chdir /root/antidote --startas bin/antidote -- foreground -kernel logger_level debug -antidote sync_log false >> /root/antidote/antidote.daemon.log 2>&1"

STDIN:
null

STDOUT:


STDERR:

        at slingshot.support$stack_trace.invoke(support.clj:201)
        at jepsen.control.core$throw_on_nonzero_exit.invokeStatic(core.clj:160)
        at jepsen.control.core$throw_on_nonzero_exit.invoke(core.clj:155)
        at jepsen.control$exec_STAR_.invokeStatic(control.clj:145)
        at jepsen.control$exec_STAR_.doInvoke(control.clj:142)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at jepsen.control$exec.invokeStatic(control.clj:161)
        at jepsen.control$exec.doInvoke(control.clj:155)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at jepsen.control.util$start_daemon_BANG_.invokeStatic(util.clj:364)
        at jepsen.control.util$start_daemon_BANG_.doInvoke(util.clj:311)
        at clojure.lang.RestFn.invoke(RestFn.java:722)
        at fuzz_dist.db$db$reify__2703$fn__2707.invoke(db.clj:104)
        at fuzz_dist.db$db$reify__2703.start_BANG_(db.clj:103)
        at fuzz_dist.db$db$reify__2703.setup_BANG_(db.clj:43)
        at jepsen.db$fn__6953$G__6947__6957.invoke(db.clj:12)
        at jepsen.db$fn__6953$G__6946__6962.invoke(db.clj:12)
        at clojure.core$partial$fn__5908.invoke(core.clj:2642)
        at jepsen.control$on_nodes$fn__6824.invoke(control.clj:314)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at dom_top.core$real_pmap_helper$build_thread__406$fn__407.invoke(core.clj:152)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Could you help find what happened here? Thank you!!

**Comment by jasonqiu98** [comment]
My system: Linux Mint 21

I just followed the typical usage listed in the docs of your project. I ran `lein run serve` and then opened a new terminal to run `lein run test --workload pn-counter`, but then some error happened.

Here is the log (the setup of the Jepsen test is omitted):

```
INFO [2022-09-21 22:29:35,084] jepsen node n2 - jepsen.os.debian n2 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n5 - jepsen.os.debian n5 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n3 - jepsen.os.debian n3 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n4 - jepsen.os.debian n4 setting up debian
INFO [2022-09-21 22:29:35,084] jepsen node n1 - jepsen.os.debian n1 setting up debian
INFO [2022-09-21 22:29:35,929] jepsen test runner - jepsen.db Tearing down DB
INFO [2022-09-21 22:29:36,029] jepsen test runner - jepsen.db Setting up DB
INFO [2022-09-21 22:29:39,706] jepsen node n4 - jepsen.control.util Starting antidote
INFO [2022-09-21 22:29:39,721] jepsen test runner - jepsen.core Snarfing log files
INFO [2022-09-21 22:29:39,773] jepsen node n4 - jepsen.core downloading /root/antidote/antidote.daemon.log to antidote.daemon.log
WARN [2022-09-21 22:29:39,991] jepsen test runner - jepsen.core Test crashed!
clojure.lang.ExceptionInfo: Command exited with non-zero status 2 on node n4:
sudo -k -S -u root bash -c "cd /; NODE_NAME=antidote@n4. COOKIE=antidote start-stop-daemon --start --background --no-close --make-pidfile --exec bin/antidote  --pidfile /root/antidote/antidote.daemon.pid --chdir /root/antidote --startas bin/antidote -- foreground -kernel logger_level debug -antidote sync_log false >> /root/antidote/antidote.daemon.log 2>&1"

STDIN:
null

STDOUT:


STDERR:

        at slingshot.support$stack_trace.invoke(support.clj:201)
        at jepsen.control.core$throw_on_nonzero_exit.invokeStatic(core.clj:160)
        at jepsen.control.core$throw_on_nonzero_exit.invoke(core.clj:155)
        at jepsen.control$exec_STAR_.invokeStatic(control.clj:145)
        at jepsen.control$exec_STAR_.doInvoke(control.clj:142)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at jepsen.control$exec.invokeStatic(control.clj:161)
        at jepsen.control$exec.doInvoke(control.clj:155)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at jepsen.control.util$start_daemon_BANG_.invokeStatic(util.clj:364)
        at jepsen.control.util$start_daemon_BANG_.doInvoke(util.clj:311)
        at clojure.lang.RestFn.invoke(RestFn.java:722)
        at fuzz_dist.db$db$reify__2703$fn__2707.invoke(db.clj:104)
        at fuzz_dist.db$db$reify__2703.start_BANG_(db.clj:103)
        at fuzz_dist.db$db$reify__2703.setup_BANG_(db.clj:43)
        at jepsen.db$fn__6953$G__6947__6957.invoke(db.clj:12)
        at jepsen.db$fn__6953$G__6946__6962.invoke(db.clj:12)
        at clojure.core$partial$fn__5908.invoke(core.clj:2642)
        at jepsen.control$on_nodes$fn__6824.invoke(control.clj:314)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at dom_top.core$real_pmap_helper$build_thread__406$fn__407.invoke(core.clj:152)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
ERROR [2022-09-21 22:29:39,992] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
clojure.lang.ExceptionInfo: Command exited with non-zero status 2 on node n4:
sudo -k -S -u root bash -c "cd /; NODE_NAME=antidote@n4. COOKIE=antidote start-stop-daemon --start --background --no-close --make-pidfile --exec bin/antidote  --pidfile /root/antidote/antidote.daemon.pid --chdir /root/antidote --startas bin/antidote -- foreground -kernel logger_level debug -antidote sync_log false >> /root/antidote/antidote.daemon.log 2>&1"

STDIN:
null

STDOUT:


STDERR:

        at slingshot.support$stack_trace.invoke(support.clj:201)
        at jepsen.control.core$throw_on_nonzero_exit.invokeStatic(core.clj:160)
        at jepsen.control.core$throw_on_nonzero_exit.invoke(core.clj:155)
        at jepsen.control$exec_STAR_.invokeStatic(control.clj:145)
        at jepsen.control$exec_STAR_.doInvoke(control.clj:142)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at jepsen.control$exec.invokeStatic(control.clj:161)
        at jepsen.control$exec.doInvoke(control.clj:155)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at jepsen.control.util$start_daemon_BANG_.invokeStatic(util.clj:364)
        at jepsen.control.util$start_daemon_BANG_.doInvoke(util.clj:311)
        at clojure.lang.RestFn.invoke(RestFn.java:722)
        at fuzz_dist.db$db$reify__2703$fn__2707.invoke(db.clj:104)
        at fuzz_dist.db$db$reify__2703.start_BANG_(db.clj:103)
        at fuzz_dist.db$db$reify__2703.setup_BANG_(db.clj:43)
        at jepsen.db$fn__6953$G__6947__6957.invoke(db.clj:12)
        at jepsen.db$fn__6953$G__6946__6962.invoke(db.clj:12)
        at clojure.core$partial$fn__5908.invoke(core.clj:2642)
        at jepsen.control$on_nodes$fn__6824.invoke(control.clj:314)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at dom_top.core$real_pmap_helper$build_thread__406$fn__407.invoke(core.clj:152)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:671)
        at clojure.core$bound_fn_STAR_$fn__5818.doInvoke(core.clj:2020)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Could you help find what happened here? Thank you!!

**Comment by nurturenature** [comment]
Hi,

Thanks for giving the repository a try.

I just tried it with my Debian development machine and it worked :thinking: 

Jepsen appears to be running correctly.

It's failing when it's trying to start AntidoteDB on each node.

The above errors show it happening on node n4.

With the web server running on the control node,
Do `bin/web` on your host machine to bring up the test results.

You should see the node n4 logs for AntidoteDB.

Maybe they provide more information re the startup failure?

**Comment by jasonqiu98** [comment]
Thank you for your help! I solved this problem by changing `db/build-db` line 36

from

```
cd /antidote-src && make rel
```

to

```
cd /antidote-src && rebar3 release
```

This error happened because the `make rel` in AntidoteDB doesn't work correctly (right now) and AntidoteDB wasn't actually installed on DB nodes. I just changed `make rel` to its raw instruction and then everything works fine :)

**Comment by nurturenature** [comment]
Good catch!

I'll close this issue as resolved.
